// ─── PERSONAL ────────────────────────────────────────────────────────────────
export const personal = {
  name:     'Avula Chandu',
  title:    'Junior Web Developer',
  subtitle: 'MERN Stack · AI & DS Student',
  email:    'chanduavula007@gmail.com',
  phone:    '+91 8688157969',
  location: 'Andhra Pradesh, India',
  github:   'https://github.com/dashboard',
  linkedin: 'https://in.linkedin.com/in/chandu-avula',
  dob:      '23 June 2005',
  college:  'NBKRIST, Nellore',
  branch:   'B.Tech – AI & Data Science (2nd Year)',
  apaarId:  '282393624334',
};

// ─── NAV SECTIONS (slide IDs) ────────────────────────────────────────────────
export const sections = [
  { id: 'home',           label: 'Home' },
  { id: 'about',          label: 'About' },
  { id: 'skills',         label: 'Skills' },
  { id: 'projects',       label: 'Projects' },
  { id: 'certifications', label: 'Certifications' },
  { id: 'contact',        label: 'Contact' },
];

// ─── SKILLS ──────────────────────────────────────────────────────────────────
export const skillCategories = [
  {
    title: 'Programming',
    icon: '🐍',
    skills: [
      { name: 'Python',     level: 85 },
      { name: 'JavaScript', level: 78 },
      { name: 'Java',       level: 65 },
      { name: 'C',          level: 60 },
    ],
  },
  {
    title: 'Frontend',
    icon: '🎨',
    skills: [
      { name: 'React.js',    level: 82 },
      { name: 'HTML5',       level: 90 },
      { name: 'CSS3',        level: 85 },
      { name: 'Tailwind CSS', level: 78 },
    ],
  },
  {
    title: 'Backend & DB',
    icon: '⚙️',
    skills: [
      { name: 'Node.js',    level: 78 },
      { name: 'Express.js', level: 75 },
      { name: 'MongoDB',    level: 78 },
      { name: 'MySQL',      level: 70 },
    ],
  },
  {
    title: 'Tools',
    icon: '🛠️',
    skills: [
      { name: 'Git & GitHub', level: 82 },
      { name: 'Power BI',     level: 75 },
      { name: 'VS Code',      level: 92 },
      { name: 'Kiro (AI IDE)', level: 80 },
    ],
  },
];

// ─── PROJECTS ─────────────────────────────────────────────────────────────────
export const projects = [
  {
    id: 1,
    title: 'Portfolio Website',
    desc: 'Personal portfolio built with React and Tailwind CSS featuring slide-based sections, smooth animations, certificate gallery and a fully responsive dark theme.',
    tags: ['React.js', 'Tailwind CSS', 'Vite'],
    icon: '🌐',
    gradient: 'from-primary to-primary-dark',
    github: 'https://github.com/dashboard',
    live: 'https://chanduportfolio7.netlify.app/',
  },
  {
    id: 2,
    title: 'MERN Blog App',
    desc: 'Full-featured blog application with user authentication, CRUD operations, a rich-text editor and a RESTful API backend powered by Express and MongoDB.',
    tags: ['MongoDB', 'Express', 'React', 'Node.js'],
    icon: '📝',
    gradient: 'from-emerald-500 to-teal-600',
    github: '#',
    live: '#',
  },
  {
    id: 3,
    title: 'Power BI Dashboard',
    desc: 'Interactive data analytics dashboard built with Microsoft Power BI and Copilot integration for AI-driven insights and automated report generation.',
    tags: ['Power BI', 'Microsoft Copilot', 'DAX'],
    icon: '📊',
    gradient: 'from-gold to-amber-500',
    github: '#',
    live: '#',
  },
];

// ─── CERTIFICATIONS ───────────────────────────────────────────────────────────
// imageNote: set imageUrl to a real hosted image path once you upload certificate scans
export const certifications = [
  // ── ACADEMIC ────────────────────────────────────────
  {
    id: 1,
    title: 'MERN Full Stack Development',
    issuer: 'GeeksforGeeks (IBM Certification)',
    badge: '🏅 Certified',
    year: '2025',
    icon: '🟢',
    gradient: 'from-emerald-500 to-teal-600',
    verifyUrl: 'https://media.geeksforgeeks.org/courses/certificates/087aa7fbf6e8c0dfa1ea10f4043f77a6.pdf',
    imageUrl: '/certs/cert-1-mern-gfg.jpg',
    tags: ['MongoDB', 'Express', 'React', 'Node.js'],
    category: 'Academic',
    type: 'achievement',
  },
  {
    id: 2,
    title: 'Copilot for Power BI',
    issuer: 'Microsoft via Coursera',
    badge: '✅ Verified',
    year: 'Nov 2025',
    icon: '📊',
    gradient: 'from-yellow-500 to-amber-500',
    verifyUrl: 'https://coursera.org/verify/YPXT3JTXMGPV',
    imageUrl: '/certs/cert-2-powerbi-microsoft.jpg',
    tags: ['Power BI', 'Copilot', 'Data Analytics'],
    category: 'Academic',
    type: 'achievement',
  },
  {
    id: 22,
    title: 'JavaScript & Power BI',
    issuer: 'Infosys Springboard',
    badge: '✅ Completed',
    year: '2024',
    icon: '📜',
    gradient: 'from-blue-500 to-indigo-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-22-infosys-js-powerbi.jpg',
    tags: ['JavaScript', 'Power BI', 'Infosys'],
    category: 'Academic',
    type: 'achievement',
  },
  {
    id: 23,
    title: 'Blockchain and Its Applications',
    issuer: 'NPTEL — IIT Kharagpur',
    badge: '✅ Score: 53%',
    year: 'Jan–Apr 2025',
    icon: '🔗',
    gradient: 'from-violet-500 to-purple-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-23-nptel-blockchain.jpg',
    tags: ['Blockchain', 'NPTEL', 'IIT Kharagpur', 'Roll: NPTEL25CS08S553601006'],
    category: 'Academic',
    type: 'achievement',
  },
  {
    id: 3,
    title: 'APAAR Academic Registry',
    issuer: 'Ministry of Education, Govt. of India',
    badge: '🔏 Digitally Signed',
    year: 'Nov 2025',
    icon: '🎓',
    gradient: 'from-blue-500 to-indigo-600',
    verifyUrl: '#',
    imageUrl: null,
    tags: ['ID: 282393624334'],
    category: 'Academic',
    type: 'achievement',
  },

  // ── TABLE TENNIS ─────────────────────────────────────
  {
    id: 4,
    title: 'QISFEST 2025 — 1st Place, Table Tennis',
    issuer: 'QIS Educational Institutions, Ongole',
    badge: '🥇 Winner',
    year: 'Feb 2025',
    icon: '🏓',
    gradient: 'from-yellow-400 to-amber-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-4-qisfest-2025-ind.jpg',
    tags: ['Table Tennis', 'National Level', 'NBKRIST'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 5,
    title: 'QISFEST 2025 — 1st Place, Table Tennis (Team)',
    issuer: 'QIS Educational Institutions, Ongole',
    badge: '🥇 Winner',
    year: 'Feb 2025',
    icon: '🏓',
    gradient: 'from-yellow-400 to-amber-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-5-qisfest-2025-team.jpg',
    tags: ['Table Tennis', 'Team Event', 'NBKRIST'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 6,
    title: 'QISFEST 2024 — 2nd Place, Sports Event',
    issuer: 'QIS Educational Institutions, Ongole',
    badge: '🥈 Runner-Up',
    year: 'Feb 2024',
    icon: '🏓',
    gradient: 'from-slate-400 to-slate-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-6-qisfest-2024.jpg',
    tags: ['Sports', 'AP Intra State', 'NBKRIST'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 7,
    title: 'JNTUA Merit — Table Tennis, South Zone',
    issuer: 'JNTUA Anantapur — VIT Vellore',
    badge: '3rd Round',
    year: 'Dec 2024',
    icon: '🏓',
    gradient: 'from-red-500 to-rose-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-7-tt-jntua-south.jpg',
    tags: ['Table Tennis', 'South Zone', 'VIT Vellore'],
    category: 'Sports',
    type: 'achievement',
  },
  {
    id: 8,
    title: 'JNTUA — Table Tennis Inter-Collegiate',
    issuer: 'Sri Venkateswara College of Engineering, Tirupati',
    badge: 'Participation',
    year: 'Oct 2024',
    icon: '🏓',
    gradient: 'from-blue-500 to-indigo-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-8-tt-jntua-svce.jpg',
    tags: ['Table Tennis', 'IUT Selections', 'AI & DS'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 9,
    title: 'School Games AP — Table Tennis (YSR Cup)',
    issuer: 'Govt. of AP — 65th Inter District',
    badge: 'Participation',
    year: 'Dec 2019',
    icon: '🏓',
    gradient: 'from-green-600 to-emerald-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-9-tt-ap-ysr.jpg',
    tags: ['Table Tennis', 'Under 17', 'Nellore District'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 10,
    title: 'West Godavari SGF — Table Tennis (CM Cup)',
    issuer: 'School Games Federation of West Godavari District',
    badge: 'Participation',
    year: 'Nov 2018',
    icon: '🏓',
    gradient: 'from-teal-500 to-cyan-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-10-tt-wgodavari.jpg',
    tags: ['Table Tennis', '64th CM Cup', 'Inter District'],
    category: 'Sports',
    type: 'participation',
  },

  // ── KHO-KHO ──────────────────────────────────────────
  {
    id: 11,
    title: 'JNTUA Merit — Kho-Kho, South Zone',
    issuer: 'JNTUA — Central University of Tamil Nadu, Thiruvarur',
    badge: '1st Round',
    year: 'Dec 2024',
    icon: '🏃',
    gradient: 'from-orange-500 to-red-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-11-khokho-jntua-south.jpg',
    tags: ['Kho-Kho', 'South Zone', 'NBKRIST'],
    category: 'Sports',
    type: 'achievement',
  },
  {
    id: 12,
    title: 'JNTUA (NBKRIST) — Kho-Kho Inter-Collegiate',
    issuer: 'N.B.K.R. Institute of Science & Technology, Vidyanagar',
    badge: 'Participation',
    year: 'Feb 2024',
    icon: '🏃',
    gradient: 'from-purple-500 to-violet-600',
    verifyUrl: '#',
    imageUrl: null,
    tags: ['Kho-Kho', 'JNTUA IUT', 'AI & DS'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 13,
    title: 'School Games AP — Kho-Kho, 65th Inter District',
    issuer: 'School Games Federation of Andhra Pradesh',
    badge: 'Participation',
    year: 'Dec 2019',
    icon: '🏃',
    gradient: 'from-indigo-500 to-blue-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-13-khokho-ap.jpg',
    tags: ['Kho-Kho', 'Under 17', 'Nellore District'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 14,
    title: 'APSWREI — Kho-Kho Zone-III Winners',
    issuer: 'APSWREI Society Amaravati, Velugonda, Prakasam',
    badge: '🏆 Winners',
    year: 'Sep 2018',
    icon: '🏃',
    gradient: 'from-yellow-500 to-lime-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-14-apswrei-khokho-winners.jpg',
    tags: ['Kho-Kho', '5th Zonal Level', 'AP Balayogi Gurukulam'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 15,
    title: 'APSWREI — Kho-Kho Zone-III Participation',
    issuer: 'APSWREI Society Amaravati, Velugonda, Prakasam',
    badge: 'Participation',
    year: 'Sep 2018',
    icon: '🏃',
    gradient: 'from-teal-400 to-green-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-15-apswrei-participation.jpg',
    tags: ['Kho-Kho', '5th Zonal Level', 'Zone-III'],
    category: 'Sports',
    type: 'participation',
  },

  // ── OTHER SPORTS ─────────────────────────────────────
  {
    id: 16,
    title: 'National Sports Day — Certificate of Merit',
    issuer: 'District Sports Authority, SPS Nellore',
    badge: '🏅 Winner / Runner-Up',
    year: 'Aug 2018',
    icon: '🏑',
    gradient: 'from-green-600 to-teal-700',
    verifyUrl: '#',
    imageUrl: '/certs/cert-16-national-sports-day.jpg',
    tags: ['Kho-Kho', 'A.C.S.R Sports Complex', 'Nellore'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 17,
    title: '8th Junior Inter District Softball Championship',
    issuer: 'Softball Association of Vizianagaram District',
    badge: 'Participation',
    year: 'Nov 2021',
    icon: '🥎',
    gradient: 'from-purple-600 to-fuchsia-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-17-softball.jpg',
    tags: ['Softball', 'Boys & Girls', '2021–22'],
    category: 'Sports',
    type: 'participation',
  },

  // ── SCIENCE ──────────────────────────────────────────
  {
    id: 18,
    title: 'India International Science Festival 2019',
    issuer: 'Ministry of Science & Technology, Govt. of India',
    badge: 'Participation',
    year: 'Nov 2019',
    icon: '🔬',
    gradient: 'from-cyan-500 to-blue-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-18-iisf.jpg',
    tags: ['IISF-19', 'Kolkata', 'C.V. Raman House'],
    category: 'Science',
    type: 'participation',
  },
  {
    id: 19,
    title: "27th National Children's Science Congress",
    issuer: 'APCOST / DST — SPSR Nellore District',
    badge: 'Participation',
    year: 'Nov 2019',
    icon: '🧪',
    gradient: 'from-emerald-500 to-green-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-19-science-congress.jpg',
    tags: ["Science Congress", 'Waste to Wealth', 'NCSC-2019'],
    category: 'Science',
    type: 'participation',
  },

  // ── SOCIAL ───────────────────────────────────────────
  {
    id: 20,
    title: 'Blood Donation — AP Vaidya Vidhana Parishad',
    issuer: 'Area Hospital Blood Bank, Gudur, Nellore',
    badge: '❤️ Voluntary Donor',
    year: '2024',
    icon: '🩸',
    gradient: 'from-red-600 to-rose-600',
    verifyUrl: '#',
    imageUrl: '/certs/cert-20-blood-ap.jpg',
    tags: ['Blood Donation', 'NBKR Institute', 'Reg No: 366'],
    category: 'Social',
    type: 'achievement',
  },
  {
    id: 21,
    title: 'Blood Donation — MediPulse Blood Centre',
    issuer: 'MediPulse Blood Centre, Gudur, Tirupati District',
    badge: '❤️ Appreciation',
    year: 'Feb 2025',
    icon: '🩸',
    gradient: 'from-pink-600 to-red-500',
    verifyUrl: '#',
    imageUrl: '/certs/cert-21-blood-medipulse.jpg',
    tags: ['Blood Donation', 'Voluntary Donor', '20 Feb 2025'],
    category: 'Social',
    type: 'achievement',
  },
];

export const CERT_CATEGORIES = ['All', 'Academic', 'Sports', 'Science', 'Social'];
