// ─── PERSONAL ────────────────────────────────────────────────────────────────
export const personal = {
  name: 'Avula Chandu',
  title: 'Full Stack Developer',
  subtitle: 'MERN Stack | AI & DS Student',
  email: 'avulachandu@gmail.com',
  location: 'Andhra Pradesh, India',
  github: 'https://github.com',
  linkedin: 'https://linkedin.com',
  dob: '23 June 2005',
  college: 'NBKRIST, Nellore',
  branch: 'B.Tech – AI & Data Science (2nd Year)',
  apaarId: '282393624334',
};

// ─── SKILLS ──────────────────────────────────────────────────────────────────
export const skillCategories = [
  {
    title: 'Frontend',
    icon: '🎨',
    skills: [
      { name: 'React.js',   level: 85 },
      { name: 'HTML5',      level: 90 },
      { name: 'CSS3',       level: 85 },
      { name: 'JavaScript', level: 80 },
    ],
  },
  {
    title: 'Backend',
    icon: '⚙️',
    skills: [
      { name: 'Node.js',    level: 80 },
      { name: 'Express.js', level: 78 },
      { name: 'REST APIs',  level: 82 },
    ],
  },
  {
    title: 'Database',
    icon: '🗄️',
    skills: [
      { name: 'MongoDB',  level: 80 },
      { name: 'MySQL',    level: 75 },
      { name: 'SQLite',   level: 70 },
    ],
  },
  {
    title: 'Tools',
    icon: '🛠️',
    skills: [
      { name: 'Git',      level: 80 },
      { name: 'Docker',   level: 65 },
      { name: 'Power BI', level: 75 },
      { name: 'VS Code',  level: 92 },
    ],
  },
];

// ─── PROJECTS ─────────────────────────────────────────────────────────────────
export const projects = [
  {
    id: 1,
    title: 'Portfolio Website',
    desc: 'Personal portfolio built with React + Tailwind CSS. Smooth animations, fully responsive, dark-mode theme.',
    tags: ['React.js', 'Tailwind CSS', 'Vite'],
    icon: '🌐',
    color: 'from-primary to-blue-500',
    github: '#',
    live: '#',
  },
  {
    id: 2,
    title: 'MERN Blog App',
    desc: 'Full-featured blog with user auth, CRUD posts, rich-text editor and RESTful API backend.',
    tags: ['MongoDB', 'Express', 'React', 'Node.js'],
    icon: '📝',
    color: 'from-green-500 to-teal-500',
    github: '#',
    live: '#',
  },
  {
    id: 3,
    title: 'Power BI Dashboard',
    desc: 'Interactive analytics dashboard using Microsoft Power BI Copilot for AI-driven insights.',
    tags: ['Power BI', 'Microsoft Copilot', 'DAX'],
    icon: '📊',
    color: 'from-yellow-500 to-orange-500',
    github: '#',
    live: '#',
  },
];

// ─── CERTIFICATIONS ───────────────────────────────────────────────────────────
// type: 'winner' | 'achievement' | 'participation'
export const certifications = [
  // ── ACADEMIC / TECH ─────────────────────────────────
  {
    id: 1,
    title: 'MERN Full Stack Development',
    issuer: 'GeeksforGeeks (IBM Certification)',
    badge: '🏅 Certified',
    year: '2025',
    icon: '🟢',
    color: 'from-green-500 to-teal-500',
    verifyUrl: 'https://media.geeksforgeeks.org/courses/certificates/087aa7fbf6e8c0dfa1ea10f4043f77a6.pdf',
    tags: ['MongoDB', 'Express', 'React', 'Node.js'],
    category: 'Academic',
    type: 'achievement',
  },
  {
    id: 2,
    title: 'Copilot for Power BI',
    issuer: 'Microsoft via Coursera',
    badge: '✅ Verified',
    year: 'Nov 2025',
    icon: '📊',
    color: 'from-yellow-500 to-orange-500',
    verifyUrl: 'https://coursera.org/verify/YPXT3JTXMGPV',
    tags: ['Power BI', 'Copilot', 'Data Analytics'],
    category: 'Academic',
    type: 'achievement',
  },
  {
    id: 3,
    title: 'APAAR Academic Registry',
    issuer: 'Ministry of Education, Govt. of India',
    badge: '🔏 Digitally Signed',
    year: 'Nov 2025',
    icon: '🎓',
    color: 'from-blue-500 to-indigo-500',
    verifyUrl: '#',
    tags: ['ID: 282393624334'],
    category: 'Academic',
    type: 'achievement',
  },

  // ── TABLE TENNIS ─────────────────────────────────────
  {
    id: 4,
    title: 'QISFEST 2025 — 1st Place, Table Tennis',
    issuer: 'QIS Educational Institutions, Ongole',
    badge: '🥇 Winner',
    year: 'Feb 2025',
    icon: '🏓',
    color: 'from-yellow-400 to-amber-500',
    verifyUrl: '#',
    tags: ['Table Tennis', 'National Level', 'NBKRIST'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 5,
    title: 'QISFEST 2025 — 1st Place, Table Tennis (Team)',
    issuer: 'QIS Educational Institutions, Ongole',
    badge: '🥇 Winner',
    year: 'Feb 2025',
    icon: '🏓',
    color: 'from-yellow-400 to-amber-500',
    verifyUrl: '#',
    tags: ['Table Tennis', 'Team Event', 'NBKRIST'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 6,
    title: 'QISFEST 2024 — 2nd Place, Sports Event',
    issuer: 'QIS Educational Institutions, Ongole',
    badge: '🥈 Runner-Up',
    year: 'Feb 2024',
    icon: '🏓',
    color: 'from-slate-400 to-slate-500',
    verifyUrl: '#',
    tags: ['Sports', 'AP Intra State', 'NBKRIST'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 7,
    title: 'JNTUA Merit — Table Tennis (South Zone)',
    issuer: 'JNTUA Anantapur — VIT Vellore',
    badge: '3rd Round',
    year: 'Dec 2024',
    icon: '🏓',
    color: 'from-red-500 to-rose-600',
    verifyUrl: '#',
    tags: ['Table Tennis', 'South Zone', 'VIT Vellore'],
    category: 'Sports',
    type: 'achievement',
  },
  {
    id: 8,
    title: 'JNTUA — Table Tennis Inter-Collegiate',
    issuer: 'Sri Venkateswara College of Engineering, Tirupati',
    badge: 'Participation',
    year: 'Oct 2024',
    icon: '🏓',
    color: 'from-blue-500 to-indigo-500',
    verifyUrl: '#',
    tags: ['Table Tennis', 'IUT Selections', 'AI & DS'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 9,
    title: 'School Games AP — Table Tennis (YSR Cup)',
    issuer: 'Govt. of AP — 65th Inter District',
    badge: 'Participation',
    year: 'Dec 2019',
    icon: '🏓',
    color: 'from-green-600 to-emerald-500',
    verifyUrl: '#',
    tags: ['Table Tennis', 'Under 17', 'Nellore District'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 10,
    title: 'West Godavari SGF — Table Tennis (CM Cup)',
    issuer: 'School Games Federation of West Godavari District',
    badge: 'Participation',
    year: 'Nov 2018',
    icon: '🏓',
    color: 'from-teal-500 to-cyan-500',
    verifyUrl: '#',
    tags: ['Table Tennis', '64th CM Cup', 'Inter District'],
    category: 'Sports',
    type: 'participation',
  },

  // ── KHO-KHO ──────────────────────────────────────────
  {
    id: 11,
    title: 'JNTUA Merit — Kho-Kho (South Zone)',
    issuer: 'JNTUA — Central University of Tamil Nadu, Thiruvarur',
    badge: '1st Round',
    year: 'Dec 2024',
    icon: '🏃',
    color: 'from-orange-500 to-red-500',
    verifyUrl: '#',
    tags: ['Kho-Kho', 'South Zone', 'NBKRIST'],
    category: 'Sports',
    type: 'achievement',
  },
  {
    id: 12,
    title: 'JNTUA (NBKRIST) — Kho-Kho Inter-Collegiate',
    issuer: 'N.B.K.R. Institute of Science & Technology, Vidyanagar',
    badge: 'Participation',
    year: 'Feb 2024',
    icon: '🏃',
    color: 'from-purple-500 to-violet-600',
    verifyUrl: '#',
    tags: ['Kho-Kho', 'JNTUA IUT', 'AI & DS'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 13,
    title: 'School Games AP — Kho-Kho (65th Inter District)',
    issuer: 'School Games Federation of Andhra Pradesh',
    badge: 'Participation',
    year: 'Dec 2019',
    icon: '🏃',
    color: 'from-indigo-500 to-blue-500',
    verifyUrl: '#',
    tags: ['Kho-Kho', 'Under 17', 'Nellore District'],
    category: 'Sports',
    type: 'participation',
  },
  {
    id: 14,
    title: 'APSWREI — Kho-Kho Zone-III Winners',
    issuer: 'APSWREI Society Amaravati, Velugonda, Prakasam',
    badge: '🏆 Winners',
    year: 'Sep 2018',
    icon: '🏃',
    color: 'from-yellow-500 to-lime-500',
    verifyUrl: '#',
    tags: ['Kho-Kho', '5th Zonal Level', 'AP Balayogi Gurukulam'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 15,
    title: 'APSWREI — Kho-Kho Zone-III Participation',
    issuer: 'APSWREI Society Amaravati, Velugonda, Prakasam',
    badge: 'Participation',
    year: 'Sep 2018',
    icon: '🏃',
    color: 'from-teal-400 to-green-500',
    verifyUrl: '#',
    tags: ['Kho-Kho', '5th Zonal Level', 'Zone-III'],
    category: 'Sports',
    type: 'participation',
  },

  // ── OTHER SPORTS ─────────────────────────────────────
  {
    id: 16,
    title: 'National Sports Day — Certificate of Merit',
    issuer: 'District Sports Authority, SPS Nellore',
    badge: '🏅 Winner/Runner-Up',
    year: 'Aug 2018',
    icon: '🏑',
    color: 'from-green-600 to-teal-600',
    verifyUrl: '#',
    tags: ['Kho-Kho', 'A.C.S.R Sports Complex', 'Nellore'],
    category: 'Sports',
    type: 'winner',
  },
  {
    id: 17,
    title: '8th Junior Inter District Softball Championship',
    issuer: 'Softball Association of Vizianagaram District',
    badge: 'Participation',
    year: 'Nov 2021',
    icon: '🥎',
    color: 'from-purple-600 to-fuchsia-500',
    verifyUrl: '#',
    tags: ['Softball', 'Boys & Girls', '2021-22'],
    category: 'Sports',
    type: 'participation',
  },

  // ── SCIENCE ──────────────────────────────────────────
  {
    id: 18,
    title: 'India International Science Festival 2019',
    issuer: 'Ministry of Science & Technology, Govt. of India',
    badge: 'Participation',
    year: 'Nov 2019',
    icon: '🔬',
    color: 'from-cyan-500 to-blue-600',
    verifyUrl: '#',
    tags: ['IISF-19', 'Kolkata', 'C.V. Raman House'],
    category: 'Science',
    type: 'participation',
  },
  {
    id: 19,
    title: "27th National Children's Science Congress",
    issuer: 'APCOST / DST — SPSR Nellore District',
    badge: 'Participation',
    year: 'Nov 2019',
    icon: '🧪',
    color: 'from-emerald-500 to-green-600',
    verifyUrl: '#',
    tags: ['Science Congress', 'Waste to Wealth', 'NCSC-2019'],
    category: 'Science',
    type: 'participation',
  },

  // ── SOCIAL ───────────────────────────────────────────
  {
    id: 20,
    title: 'Blood Donation — AP Vaidya Vidhana Parishad',
    issuer: 'Area Hospital Blood Bank, Gudur, Nellore',
    badge: '❤️ Voluntary Donor',
    year: '2024',
    icon: '🩸',
    color: 'from-red-600 to-rose-500',
    verifyUrl: '#',
    tags: ['Blood Donation', 'NBKR Institute', 'Reg No: 366'],
    category: 'Social',
    type: 'achievement',
  },
  {
    id: 21,
    title: 'Blood Donation — MediPulse Blood Centre',
    issuer: 'MediPulse Blood Centre, Gudur, Tirupati District',
    badge: '❤️ Appreciation',
    year: 'Feb 2025',
    icon: '🩸',
    color: 'from-pink-600 to-red-500',
    verifyUrl: '#',
    tags: ['Blood Donation', 'Voluntary Donor', '20 Feb 2025'],
    category: 'Social',
    type: 'achievement',
  },
];

export const CERT_CATEGORIES = ['All', 'Academic', 'Sports', 'Science', 'Social'];
